# Generated by Django 6.0.3 on 2026-03-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_instructor_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='selected_choice',
        ),
        migrations.AddField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(to='course.choice'),
        ),
    ]
