# Generated by Django 6.0.3 on 2026-03-28 03:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_submission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='course.course'),
        ),
        migrations.AddField(
            model_name='learner',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='learners', to='course.course'),
        ),
        migrations.AddField(
            model_name='learner',
            name='occupation',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='learner',
            name='social_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 28, 3, 49, 46, 773102, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='course.course'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='course.question'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='result',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='course.course'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='course.student'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(related_name='submissions', to='course.choice'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='course.question'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='course.student'),
        ),
    ]
