# Generated by Django 6.0.3 on 2026-03-28 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_instructor_course_learner_courses_learner_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_at',
        ),
    ]
