# Generated by Django 6.0.3 on 2026-03-28 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_submission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 28, 4, 0, 17, 758443, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
